import streamlit as st
import pandas as pd
from fpdf import FPDF
import base64
import os

import streamlit as st

# THIS MUST BE THE FIRST THING ON THE PAGE
if "authenticated" not in st.session_state or not st.session_state["authenticated"]:
    st.warning("🔒 Access Denied. Please login on the Home page.")
    st.image("https://cdn-icons-png.flaticon.com/512/3064/3064155.png", width=100) # Lock icon
    if st.button("Go to Home Page"):
        st.switch_page("Home.py")
    st.stop() # This kills the script right here so no charts load

# 1. SECURITY CHECK
if "authenticated" not in st.session_state:
    st.warning("Please login on the Home page first.")
    st.stop()

st.set_page_config(page_title="Business Reporting", layout="centered")

st.title("📄 Professional Business Report")
st.write("Generate a branded PDF summary for your fashion business stakeholders.")

# 2. DATA LOADING LOGIC (Must match Dashboard and Management pages)
DATA_PATH = "data/instagram_data.csv"

if os.path.exists(DATA_PATH):
    df = pd.read_csv(DATA_PATH)
    # Calculate Engagement dynamically
    df['engagement'] = df['likes'] + df['comments'] + df['shares'] + df['saves']
else:
    st.info("👋 Please upload your data in the **Data Management** page first to generate a report.")
    st.stop()

# 3. REPORT CUSTOMIZATION
st.divider()
report_name = st.text_input("Enter Client/Business Name", "Joey Clothing")
report_date = st.date_input("Report Date")

if st.button("Generate & Download PDF Report"):
    with st.spinner("Compiling data science insights..."):
        # --- Data Analysis for PDF ---
        total_posts = len(df)
        avg_eng = int(df['engagement'].mean())
        # Find best and worst content dynamically
        content_stats = df.groupby('content_type')['engagement'].mean()
        best_content = content_stats.idxmax()
        worst_content = content_stats.idxmin()
        
        # --- PDF Construction ---
        pdf = FPDF()
        pdf.add_page()
        
        # Branded Header
        pdf.set_font("Arial", 'B', 24)
        pdf.set_text_color(40, 40, 40) # Dark Grey
        pdf.cell(200, 20, txt=f"{report_name}", ln=True, align='C')
        
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(200, 10, txt="Social Media Performance Audit", ln=True, align='C')
        pdf.cell(200, 10, txt=f"Date: {report_date}", ln=True, align='C')
        pdf.ln(15)
        
        # Metrics Section
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, txt="1. EXECUTIVE SUMMARY", ln=True)
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 10, txt=f"- Total Content Pieces Analyzed: {total_posts}", ln=True)
        pdf.cell(0, 10, txt=f"- Average Engagement Benchmark: {avg_eng} interactions per post", ln=True)
        pdf.cell(0, 10, txt=f"- Optimal Content Format: {best_content}", ln=True)
        pdf.ln(10)
        
        # Strategic Recommendations (DYNAMIC)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, txt="2. STRATEGIC RECOMMENDATIONS", ln=True)
        pdf.set_font("Arial", size=11)
        
        rec1 = f"Priority: Focus production on {best_content}s as they drive the highest audience retention."
        rec2 = f"Optimization: Reduce resources spent on {worst_content}s or redesign their creative approach."
        rec3 = "Growth: Maintain consistent posting during peak 'High-Traffic' windows identified in the dashboard."
        
        pdf.multi_cell(0, 10, txt=f"{rec1}\n{rec2}\n{rec3}")
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 10, txt="Generated by Fashion Analytics SaaS System - Final Year Project 2026", align='C')

        # --- Output and Download ---
        # We use 'latin-1' encoding to ensure compatibility with FPDF
        pdf_output = pdf.output(dest='S').encode('latin-1')
        b64 = base64.b64encode(pdf_output).decode()
        href = f'<a href="data:application/octet-stream;base64,{b64}" download="{report_name}_Report.pdf" style="text-decoration:none;"><button style="background-color:#4CAF50; color:white; padding:10px 24px; border:none; border-radius:4px; cursor:pointer;">📥 Click Here to Download PDF Report</button></a>'
        
        st.markdown(href, unsafe_allow_html=True)
        st.success("Your professional audit is ready!")